# Generated by Django 4.0.5 on 2023-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
